### ISSUE TITLE
What is the difference between system and user segments?

### ISSUE THREAD

**Issue by reginbald** [Azure/digital-twin-model-identifier#5]
What is the difference between system and user segments?
> it is a system segment; if it begins with a letter, it is a user segment.

**Comment by jrdouceur** [comment]
Is the remainder of the paragraph unclear about this?  Repeating it here:

If a DTMI contains at least one system segment, it is a system DTMI; otherwise, it is a user DTMI. System DTMIs may be referenced in non-system DTDL model documents, but they are not permitted as "@id" values of any elements defined in non-system models; only user DTMIs are permitted.

**Comment by jrdouceur** [comment]
Closing since there is no indication that my response was insufficient.
